---
name: terraform
packages:
  - terraform
key_file_name: hashicorp-archive-keyring.gpg
gpg_key_url: https://apt.releases.hashicorp.com/gpg
repo_url: https://apt.releases.hashicorp.com
repo_type: "{{ansible_distribution_release}}"
release_channel: main
