---
repo_name: ""             # The repositoriy name
repo_key_file_name: ""    # The key name as you want to see it in your system
repo_gpg_key_url: ""      # The download gpg key URL
repo_url: ""         # The repositoriy URL
repo_type: ""        # The repositoriy distrubution or type
repo_release_channel: ""  # The release channel to use

