---
- name: "Install apt common package"
  ansible.builtin.package:
    name: "{{ neovim_system_packages }}"
    state: present

- name: "Download Neovim"
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim/releases/download/{{neovim_version}}/nvim-linux64.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: true

- name: "Install Packer plugin manager"
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ansible_user_dir}}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1

