#!/usr/bin/env bash

echo $#
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find  ~/dev/ -maxdepth 2 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

echo ${selected}
echo ${selected_name}

# if $TMUX is empty and $tmux_running is empty
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s ${selected_name} -c ${selected}
    tmux rename-window -t ${selected_name}:1 vim -c ${selected}
    tmux new-window -t ${selected_name} -n git -c ${selected}
    tmux new-window -t ${selected_name} -n shell -c ${selected}
    exit 0
fi

if ! tmux has-session -t=${selected_name} 2> /dev/null; then
    tmux new-session -ds ${selected_name} -c ${selected}
    tmux rename-window -t ${selected_name}:1 vim 
    tmux new-window -t ${selected_name} -n git -c ${selected}
    tmux new-window -t ${selected_name} -n shell -c ${selected}
fi

tmux switch-client -t ${selected_name}
