---
- hosts: localhost
  tasks:
    - name: "Install apt common package"
      become: yes
      ansible.builtin.package:
        name: "{{ system_packages }}"
        state: present

    - name: "Add new apt repository and install package"
      become: yes
      block:
        - name: "Add  Repo"
          ansible.builtin.include_role:
            name: add_apt_repo
          vars:
            key_file_name: "{{item.key_file_name}}"
            gpg_key_url: "{{item.gpg_key_url}}"
            repo_url: "{{item.repo_url}}"
            repo_type: "{{item.repo_type}}"
            release_channel: "{{item.release_channel}}"
            name: "{{item.name}}"
          loop: "{{package_from_repo}}"

        - name: "Install Packages"
          ansible.builtin.apt:
            name: "{{item.packages}}"
            update_cache: yes
          loop: "{{package_from_repo}}"

    - name: "Add user in docker group"
      become: yes
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop: "{{user_docker}}"

    - name: "Golang"
      become: yes
      block:
        ansible.builtin.include_role:
          name: golang
      when: golang

    - name: "Oh-my-ZSH"
      become: yes
      block:
        ansible.builtin.include_role:
          name: oh-my-zsh
      when: oh_my_zsh

    - name: "TMUX"
      become: yes
      block:
        ansible.builtin.include_role:
          name: tmux
      when: tmux

    - name: "Neovim"
      become: yes
      block:
        ansible.builtin.include_role:
          name: neovim
      when: neovim
        
    - name: "Download Nerd Font"
      become: yes
      block:
        ansible.builtin.include_role:
          name: nerd_font
      when: nerd_font
  
    - name: "alacritty"
      become: yes
      block:
        ansible.builtin.include_role:
          name: alacritty
      when: alacritty 
