---
alacritty_system_packages:
  - cmake
  - libfreetype6-dev  # dep for alacritty
  - libfontconfig1-dev  # dep for alacritty
  - libxcb-xfixes0-dev  # dep for alacritty
  - libxkbcommon-dev  # dep for alacritty
  - cargo  # dep for alacritty
  - curl
  - git
